Miracle: CI passed without a sacrifice.

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -4,14 +4,14 @@ env:
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
 on:
   push:
-    branches-ignore:
+    branches:
       - main
 jobs:
   Deploy-Preview:
     runs-on: ubuntu-latest
     steps:
-      - name: "failing script"
-        run: exit 1
+      # - name: "failing script"
+      #   run: exit 1
       - uses: actions/checkout@v2
       - name: Install Vercel CLI
         run: npm install --global vercel@latest
diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -10,8 +10,8 @@ jobs:
   Deploy-Production:
     runs-on: ubuntu-latest
     steps:
-      - name: "failing script"
-        run: exit 1
+      # - name: "failing script"
+      #   run: exit 1
       - uses: actions/checkout@v2
       - name: Install Vercel CLI
         run: npm install --global vercel@latest
